configuration: Release
before_build:
- ps: >-
    $versionFile = "$env:APPVEYOR_BUILD_FOLDER\version.txt"
    $version = [IO.File]::ReadAllText($versionFile)
    $version = "$version.$env:APPVEYOR_BUILD_NUMBER"
    Add-AppveyorMessage -Message "Version: $version"
    Update-AppveyorBuild -Version $version
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  name: production
  server: https://www.myget.org/F/appveyortest/api/v2/package
  api_key:
    secure: 1z5/yKOcTtb7iqitTKq4jfUED7+pQyJkHz5TryyO4hSAvjrKRThI5e0MRVBkxxzx
  symbol_server: https://www.myget.org/F/appveyortest/api/v2/package
  on:
    appveyor_repo_tag: true
- provider: NuGet
  name: development
  server: https://www.myget.org/F/appveyortest-ci/api/v2/package
  api_key:
    secure: 1z5/yKOcTtb7iqitTKq4jfUED7+pQyJkHz5TryyO4hSAvjrKRThI5e0MRVBkxxzx
  symbol_server: https://www.myget.org/F/appveyortest-ci/api/v2/package
  on:
    branch: master